sudo: required
language: go
go:
- 1.9.2
go_import_path: v2ray.com/core
git:
  depth: 5
before_script:
- sudo ntpdate -u time.google.com
- date
script:
- go test -p 1 -tags json -v v2ray.com/core/...
after_success:
- ./testing/coverage/coverall
